[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = "dist/js"
    target = "assets/js/modules/mgallery"
  [[module.mounts]]
    source = "dist/css"
    target = "assets/scss/modules/mgallery"
  [[module.mounts]]
    source = "dist/images"
    target = "static/images"    
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
