baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-mgallery'

[module]
  replacements = 'github.com/markdumay/mod-mgallery -> ../..'
  [[module.imports]]
    path = "github.com/markdumay/mod-mgallery"